---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - switch.alexbescond.io
  resources:
  - interrupters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - switch.alexbescond.io
  resources:
  - interrupters/finalizers
  verbs:
  - update
- apiGroups:
  - switch.alexbescond.io
  resources:
  - interrupters/status
  verbs:
  - get
  - patch
  - update
